version: '3.8'
networks:
  default:
    driver: bridge
services:
  backend:
    depends_on:
      - database
    links:
      - "database:database"
    build:
      context: ./backend/api
      dockerfile: Dockerfile
    environment:
      env_file:
        .env
    ports:
      - 800:8000
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      env_file:
        .env
    ports:
      - 5432:5432
    volumes:
      - ./database/data:/var/lib/postgresql/data